version: '3.1'

services:
    flowise:
        image: flowise
        build: .
        restart: always
        environment:
            - PORT=${PORT}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
            - ./:/localfiles
