version: '3.1'

services:
    SAIA:
        image: SAIAai/SAIA
        restart: always
        environment:
            - PORT=${PORT}
            - SAIA_USERNAME=${SAIA_USERNAME}
            - SAIA_PASSWORD=${SAIA_PASSWORD}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - SAIA_SECRETKEY_OVERWRITE=${SAIA_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.SAIA:/root/.SAIA
        command: /bin/sh -c "sleep 3; SAIA start"
